---
version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config:/etc/traefik
      - /etc/localtime:/etc/localtime
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`traefik.example.com`) && PathPrefix(`/dashboard`)" # Domainnamen anpassen!
    #   - "traefik.http.routers.api.entryPoints=dashboard"
    #   - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
    #   - "traefik.http.routers.api.service=api@internal"
    #   - "traefik.http.routers.api.middlewares=api-auth"
    #   - "traefik.http.middlewares.api-auth.basicauth.users=user/pass" # Benutzer und Passwort generieren
    networks:
      - traefik_proxy
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8180:8080"
    restart: always

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge    
