{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red38\green38\blue38;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24\fsmilli12375 \cf2 \expnd0\expndtw0\kerning0
version: '3'\
\
services:\
\
  traefik:\
    image: traefik:latest\
    command: --docker --docker.domain=hakase-labs.io\
    ports:\
      - 80:80\
      - 443:443\
    networks:\
      - proxy\
    volumes:\
      - /var/run/docker.sock:/var/run/docker.sock\
      - ./traefik.toml:/traefik.toml\
      - ./acme.json:/acme.json\
    labels:\
      - "traefik.frontend.rule=Host:traefik.hakase-labs.io"\
      - "traefik.port=8080"\
    container_name: traefik\
    restart: always\
\
networks:\
  proxy:\
    external: true}